### ISSUE TITLE
biometric age key gen needs to be encrypted at rest and is not

### ISSUE THREAD

**Issue by dmore** [remko/age-plugin-se#2]
age-plugin-se keygen -o abop.biometric.age --access-control any-biometry-or-passcode
public key: es1se.............,
AGE-PLUGIN-SE-1.....................................................

maybe there is an option I am missing. if you could advise. Looks unencrypted to me.

I get it to work besides that, although with a few work-arounds, but that is a no-no for me. 

I'll wait till that is fixed to follow this then...

**Comment by remko** [comment]
Hi @dmore

I'm assuming you're talking about the `AGE-PLUGIN-SE-1` bit. This is actually an encrypted representation of the key, only usable with the particular Secure Enclave it was created with. From [Apple's Documentation](https://developer.apple.com/documentation/cryptokit/storing_cryptokit_keys_in_the_keychain):

> Keys that you store in the Secure Enclave expose a raw representation as well, but in this case the data isn’t the raw key. Instead, the Secure Enclave exports an encrypted block that only the same Secure Enclave can later use to restore the key.

That said, you should of course keep your private keys private (as you do with all other private keys)

**Comment by dmore** [comment]
Looks to me very much like a passphrase-less equivalent of an age key. When armored in age you get

cat key.age 
-----BEGIN AGE ENCRYPTED FILE-----
Y....
-----END AGE ENCRYPTED FILE-----

to use it then I need to inject the passphrase at runtime. That is what I expect on here too and that is the only way I would use age.

Is it possible to get that armor description as well so there is no doubt on the implementation because I am doubting the implementation at the moment.

**Comment by remko** [comment]
@dmore Yes, this works as usual. Just follow [the age instructions about 'Passphrase-protected key files'](https://github.com/FiloSottile/age#passphrase-protected-key-files), but replace `age-keygen` with `age-plugin-se keygen`:

```
$ age-plugin-se keygen | age -p > key.age
...
```

**Comment by dmore** [comment]
yeah that is better. is encrypted and can use armor like you indicate. will give it another go. public key is hidden this way but that is not a problem. can get to it when decrypting it.

**Comment by remko** [comment]
@dmore I looked into printing the public key when using redirection, like `age-keygen` does, but it’s too much trouble. So you’ll indeed have to decrypt the key to get the public key, or do it in 2 steps without redirection.
