### ISSUE TITLE
Why is Xcode required when installing from brew?

### ISSUE THREAD

**Issue by alexeykiselev** [remko/age-plugin-se#5]
Hello.

Thank you for the work you've done!

Could you explain why installing the plugin from brew requires Xcode? Why can't the binary file from the release simply be packaged in brew, and instead it has to be built?
Maybe a section about this should be added to the README so that other users don't have these questions?

Thank you!

**Comment by remko** [comment]
Once the project has enough stars (75), I can submit it to homebrew core. I assume it will then automatically get binary packages, and won’t need to be built from source then.

**Comment by alexeykiselev** [comment]
Added one more star :)

**Comment by alexeykiselev** [comment]
Looks like we have crossed the threshold.

**Comment by remko** [comment]
@alexeykiselev Correct. The homebrew-core PR is currently waiting to be merged, so i don't think it will take long for it to be available.

**Comment by alexeykiselev** [comment]
Thank you! And thank everybody who added stars.
